name: CI

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check Python syntax
        run: |
          python -m py_compile main.py

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check .
